export const MODALNAMES = {
  "TRIPMODAL":"TRIPMODAL",
  "COURIERTYPEMODAL":"COURIERTYPEMODAL",
  "COURIERCATEMODAL":"COURIERCATEMODAL",
  "COURIERSTAGEMODAL":"COURIERSTAGEMODAL",
  "BRANCHMODAL":"BRANCHMODAL",
  "USERMODAL":"USERMODAL",
  "WEIGHTUNITMODAL":"WEIGHTUNITMODAL",
  "COURIERPRICEMODAL":"COURIERPRICEMODAL",
  "EXTRACHARGE":"EXTRACHARGE",
  "IDTYPEMODAL":"IDTYPEMODAL",
  "SECURITYQUESTIONMODAL":"SECURITYQUESTIONMODAL",
  "PENDINGTRANSMODAL":"PENDINGTRANSMODAL",
  "INQUEUEMODAL":"INQUEUEMODAL",
  "DISPATCHMODAL":"DISPATCHMODAL",
  "INBOUNDMODAL":"INBOUNDMODAL",
  "RECEIVECOURIERMODAL":"RECEIVECOURIERMODAL",
  "COLLECTEDCOURIERMODAL":"COLLECTEDCOURIERMODAL",
  "CUSTOMERMODAL":"CUSTOMERMODAL",
  "CONSOLIDATEDPACKAGES":"CONSOLIDATEDPACKAGES",
  "LINKCONSOLIDATION":"LINKCONSOLIDATION"
}
  

  export const USERLEVEL = {
    SUPER_ADMIN:"SUPER ADMIN",
    ADMIN:"ADMIN",
    MANAGER:"MANAGER",
    SUPERVISOR:"SUPERVISOR",
    STAFF:"STAFF",
    USER:"USER",
    CASHIER:"CASHIER"
 }



 
export const COURIER_STAGES = {
  PAYMENT:"PAYMENT",
  INQUEUE:"IN QUEUE",
  DISPATCH:"DISPATCH",
  INBOUND:"IN BOUND",
  RECEIVED:"RECEIVED",
  COLLECTED:"COLLECTED"
}


export const PAYMENT_STATUS = {
  PENDING:"PENDING",
  PAID:"PAID",
}


export const USERSTATUS = {
  ACTIVE:"ACTIVE",
  INACTIVE:"INACTIVE",
  SUSPENDED:"SUSPENDED"
}